# Generated by Django 4.0.6 on 2022-12-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
