# Generated by Django 4.0.6 on 2022-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_user_about_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='iran', max_length=300, null=True),
        ),
    ]
