# Generated by Django 4.0.6 on 2022-12-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
