# Generated by Django 4.0.6 on 2022-12-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_user_sign_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='not named', max_length=300, null=True),
        ),
    ]
