# Generated by Django 4.0.6 on 2023-01-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
