# Generated by Django 4.0.6 on 2023-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0007_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to='images'),
        ),
    ]
