# Generated by Django 4.0.6 on 2023-01-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='static/assets/images/profile/profile-1.jpg', null=True, upload_to='images'),
        ),
    ]
