# Generated by Django 4.0.6 on 2023-01-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.FileField(default='images/profile-banner.jpg', null=True, upload_to='images'),
        ),
    ]
