# Generated by Django 4.0.6 on 2023-01-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
