# Generated by Django 4.0.6 on 2023-01-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0013_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
