# Generated by Django 4.0.6 on 2023-01-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0014_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
