# Generated by Django 4.0.6 on 2023-01-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0015_post_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile_picture_address',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
