# Generated by Django 4.0.6 on 2023-01-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0016_post_author_profile_picture_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_full_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
