# Generated by Django 4.0.6 on 2023-01-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0017_post_author_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_full_name',
        ),
    ]
