# Generated by Django 4.0.6 on 2023-01-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0021_user_request_usernames_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request_usernames',
        ),
    ]
