# Generated by Django 4.0.6 on 2023-02-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0022_remove_user_request_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_profile_picture_address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_username',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='home_module.user'),
        ),
    ]
